### ISSUE TITLE
Please share database as .json file

### ISSUE THREAD

**Issue by rahulmkadam92** [mitchtabian/Android-Instagram-Clone#13]
Hi Mitch,

Can you please share the structure of the database as json file ? The same one that you used in videos would be enough.

I tried creating new database file by watching your videos but its is not working perfectly...

**Comment by mitchtabian** [comment]
You need to use the app to insert data. Inserting data manually will mess
it up.

**Comment by rahulmkadam92** [comment]
Thanks
