### ISSUE TITLE
App unstability

### ISSUE THREAD

**Issue by hardheyeancar** [mitchtabian/Android-Instagram-Clone#14]
_** i have few bugs over my app..My app crashed after accessing a directory without pictures and I followed your instruction by calling the try{} and catch method but yet it glitches and the picture uploading rate is very slow,it takes so much time before successful uploading and sometimes it crashed
It doesn't display more the three pictures in the profile_fragment gridview and will only display of the photos from my firebase storage**_

**Comment by thisisyash** [comment]
It displays more than 3 pictures , you need to scroll the grid view , as the layout height is set to wrap_content intially it shows only 3 but later on while the images were loading then it continues to expand . try scrolling it down.

**Comment by almaseela** [comment]
Error:(41, 25) error: package R does not exist when I was run

**Comment by saikishorekate** [comment]
Error:(10, 33) error: cannot find symbol class R

**Comment by thisisyash** [comment]
You need to refresh the gradle

**Comment by saikishorekate** [comment]
Yes I have done that, And Sync Project with Gradle File..But it still showing the same!
Thank You for the kind replay..!

**Comment by saikishorekate** [comment]
import tabian.com.instagramclone2.R;
This is the line causing the error.
In above import code, there is 
import tabian.com.instagramclone.R;
