### ISSUE TITLE
Failed to Authenticate

### ISSUE THREAD

**Issue by gmrm** [mitchtabian/Android-Instagram-Clone#22]
not able to signup... its saying Failed to Authenticate

**Comment by banti6350** [comment]
@gmrm

Please Double Check That You have Enabled The Authencation Method In Firebase Project

**Comment by mitchtabian** [comment]
You either:
1. Tried to connect to my Firebase Project
2. Did not enable the authentication method in the firebase console
3. Did something else incorrectly
