### ISSUE TITLE
My Instagram clone

### ISSUE THREAD

**Issue by yTakkar** [mitchtabian/Android-Instagram-Clone#3]
I have also created an Instagram-clone but for web!!
Here's the link:
https://github.com/yTakkar/Instagram-clone

**Comment by postup1994** [comment]
I challenge you to make an android app for it.
Going web is slowly dying off, every stuffs now want mobile.

**Comment by yTakkar** [comment]
@postup1994  I'll look forward to building an Instagram-clone for mobile, but with React-Native!!

**Comment by postup1994** [comment]
Ok cool, i look forward to it too man.
By the way ur insta web clone is cool. Can i get the webaddress so i can signup

**Comment by yTakkar** [comment]
Thnx...
I have hosted it locally on localhost.
But you can make it your own with those 5 steps!!
:)

**Comment by postup1994** [comment]
Cool. I love the look on the web. Is there anyway i can convert to android app? Any solution??

**Comment by yTakkar** [comment]
Sorry no idea!!
