### ISSUE TITLE
Stories doesnt work 

### ISSUE THREAD

**Issue by anonym2** [mitchtabian/Android-Instagram-Clone#30]
A lot of bug in your project  picture post from gallery doesnt go to feed fragements but  only change profil pictures , story doesnbt work  cant research others peoples

**Comment by mitchtabian** [comment]
There's a lot more problems than that. It's not complete. I don't have time to work on it anymore.

**Comment by anonym2** [comment]
Thats sad you're the only we know you doing this type of job but thanks for the iniative

**Comment by charles935** [comment]
sir please complete it

**Comment by mitchtabian** [comment]
Sorry no time friends

**Comment by anonym2** [comment]
Its ok I builded it myself
