### ISSUE TITLE
Failed to Authenticate

### ISSUE THREAD

**Issue by wangkangmao** [mitchtabian/Android-Instagram-Clone#4]
Failed to Authenticate

**Comment by mitchtabian** [comment]
You need to use your own firebase project. Not mine.

**Comment by n1schal** [comment]
@mitchtabian hey, how do i set up the firebase project and configure it to use with the instagram clone?

**Comment by mitchtabian** [comment]
Have you watched the videos? Everything you need to know is in the videos.
