### ISSUE TITLE
layer-list rendering erro

### ISSUE THREAD

**Issue by sahanpasindu** [mitchtabian/Android-Instagram-Clone#8]
after putting layer-list show me error, i dont know the reason

![problem](https://user-images.githubusercontent.com/26884480/31682503-df152278-b397-11e7-96d5-857782b601a7.PNG)

**Comment by mitchtabian** [comment]
refresh it

**Comment by sahanpasindu** [comment]
**still nothing changed**

**Comment by sahanpasindu** [comment]
fixed. thank you, i miss place it to `drawable` folder
